const actionTypes = {
    SET_GAMES:"SET_GAMES",
    ADD_GAME: "ADD_GAME",
    REMOVE_GAME:"REMOVE_GAME",
    UPDATE_GAME:"UPDATE_GAME",
    SET_EDITED_GAME:"SET_EDITED_GAME",
    FETCHING_IN_PROGRESS: "FETCHING_IN_PROGRESS",
    FETCHING_COMPLETE: "FETCHING_COMPLETE",
    FETCHING_CANCELED: "FETCHING_CANCELED",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    SET_GAME_FILTER: "SET_GAME_FILTER"
}

export default actionTypes;